// <auto-generated />
using System;
using ChoucairApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChoucairApp.Infrastructure.Migrations
{
    [DbContext(typeof(ChoucairDbContext))]
    [Migration("20240705055547_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChoucairApp.Core.Domain.Entities.StatusEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Status_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Status_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status_Description");

                    b.HasKey("ID");

                    b.ToTable("Status", "system");
                });

            modelBuilder.Entity("ChoucairApp.Core.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Task_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<string>("Task_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Task_Description");

                    b.Property<DateTime>("Task_EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Task_EndDate");

                    b.Property<DateTime>("Task_StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Task_StartDate");

                    b.Property<string>("Task_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Task_Title");

                    b.HasKey("ID");

                    b.ToTable("Tasks", "system");
                });
#pragma warning restore 612, 618
        }
    }
}
